@startuml
left to right direction
!include <archimate/Archimate>

Rel_Triggering(DUB, LHR, 1)
Rel_Serving(DUB, CDG, 2)
Rel_Serving(CDG, BOS, 6)
Rel_Serving(CDG, BKK, 9)
Rel_Serving(ORD, LAS, 2)
Rel_Serving(LHR, NYC, 5)
Rel_Serving(NYC, LAS, 3)
Rel_Serving(BOS, LAX, 4)
Rel_Serving(LHR, BKK, 9)
Rel_Serving(BKK, SYD, 11)
Rel_Serving(LAX, LAS, 2)
Rel_Serving(DUB, ORD, 6)
Rel_Serving(LAX, SYD, 13)
Rel_Serving(LAS, SYD, 14)
@enduml
