name: Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-n-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests and assembly
      run: sbt assembly
    - name: Save Artifact
      uses: actions/upload-artifact@v2
      with:
        name: airport-routes-finder-0.1
        path: target/**/airport-routes-finder-0.1.jar
